### ISSUE TITLE
Restarting a campaign needs to be documented and made intuitive to users

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#102]
@velocirobbie has been writing the FabSim integration and found that the use of `work_dir` as specified in the `Campaign` constructor as the start of the path for the campaign directory to be unclear.

We should at least provide clear documentation but may want to consider a different default to '.', perhaps in conjunction with storing the working directory in the state file and over riding with constructor parameter? Or possibly having a same machine flag?

**Comment by raar1** [comment]
I've written a tutorial on restarting campaigns. Haven't thought much about the `work_dir` issue though.

**Comment by dww100** [comment]
I could pair develop something with Robbie on Monday?

**Comment by wedeling** [comment]
@raar1 where can I find your tutorial on restarting campaigns?

**Comment by raar1** [comment]
Hi @wedeling, you can find it here (it's in the dev part of the docs):
https://easyvvuq.readthedocs.io/en/dev/

It's not a great tutorial, just something I knocked together quickly, so if you have any trouble with it let me know.

**Comment by wedeling** [comment]
Hi @raar1, it worked fine for me. I've split the job submission and post processing, since it takes a bit of time for all the samples to complete on eagle. So after all jobs are submitted, I save the campaign, and I restart it when all samples have completed. When I restart the campaign, I extract the sampler and output_colums (which I need for post processing) as follows:

`    #get sampler and output columns from my_campaign object
    my_sampler = my_campaign._active_sampler
    output_columns = my_campaign._active_app_decoder.output_columns`

**Comment by raar1** [comment]
Ah great! OK, it looks like we at the very least need a my_campaign.get_active_sampler() method and something equivalent for the output_columns.

**Comment by wedeling** [comment]
@raar1 Yes, that would make my code a bit cleaner.

**Comment by raar1** [comment]
Campaign now has a `get_active_sampler()` method, and campaign restart is documented.
