### ISSUE TITLE
Sampling via FabSim

### ISSUE THREAD

**Issue by wedeling** [UCL-CCS/EasyVVUQ#127]
If I want to run an EasyVVUQ campaign on a remote resource using FabSim3, I replace the `ExecuteLocal` line with 

```
run_FabUQ_ensemble(my_campaign.campaign_dir, 'ocean', machine='eagle_vecma')
```

Where `run_FabUQ_ensemble` is just a subroutine which runs a single FabSim command line instruction:

```
#subroutine which runs the EasyVVUQ ensemble with FabSim's campaign2ensemble 
def run_FabUQ_ensemble(campaign_dir, script_name, machine = 'localhost'):
    sim_ID = campaign_dir.split('/')[-1]
    os.system("fabsim " + machine + " run_uq_ensemble:" + sim_ID + ",campaign_dir=" + campaign_dir + ",script_name=" + script_name)
```
This subroutine is located in the same file as my EasyVVUQ script, which is kind of ugly. Since this subroutine is not application specific, can we maybe move it somewhere inside EasyVVUQ? For instance `my_campaign.run_FabUQ_ensemble(...)` or maybe as a part of the sampling classes?

**Comment by dww100** [comment]
Things to do with running the application should be nowhere in the EasyVVUQ codebase ideally IMO.  We only have ExecuteLocal for testing and tutorial purposes.

Not sure whether this should be in FabSim or we could consider making a VECMA interface library or at least repository?

**Comment by wedeling** [comment]
I see your point, and now that you mention it, I remember this was also mentioned in the paper. I'll leave it as is then, it's just a single command line instruction anyway.

**Comment by djgroen** [comment]
@wedeling Actually, the point you raise is very important. Originally, we developed FabSim for command-line operation, but we realize that more and more people also want to use the toolkit through Python directly, as you have been doing now. We already made a few changes that makes this easier (e.g., that FabSim can be launched from any directory), but we haven't quite converged on the best / most elegant solution yet.

At the moment, there are two solutions that I can think of:
1. We expose FabSim commands as a Python function in a very rudimentary manner, simply mapping a Python function to os.system (like you did, but more generic, and included in a separate library file).
2. We allow for an "import fabsim" in Python. This would normally be the better option, but the problem is that FabSim3 has a lot of context-sensitive information, so just importing it in a Python script is quite likely to lead to accidents and misunderstandings... and might not help usability at all.

There may be other good options out there as well, and I'm happy to entertain any of them :).

Once we have a consensus, I'm happy to open up a corresponding ticket in the FabSim3 repo to then resolve this.

**Comment by wedeling** [comment]
@djgroen Option 1 seems ok to me, a separate library file would already clean up my code.

**Comment by djgroen** [comment]
@wedeling Okay. I will  establish that a.s.a.p. then, perhaps even this week :)

**Comment by wedeling** [comment]
cool, thanks
