### ISSUE TITLE
Nested sparse grid

### ISSUE THREAD

**Issue by wedeling** [UCL-CCS/EasyVVUQ#133]
We need to be able to pass the boolean 'growth' parameter to the PCE/SC sampler and analysis objects, in order to use sparse grids with clenshaw-curtis points, e.g.

```
        self._nodes, _ = cp.generate_quadrature(order=self.quad_order,
                                                domain=self.distribution,
                                                rule=quadrature_rule,
                                                sparse=sparse,
                                                growth=growth)
```

If set to True, clenshaw curtis points become nested, the default value is False. Also, I get incorrect mean and variance if `growth=False` and `rule="C"`.

**Comment by jlakhlili** [comment]
Thanks Wounter! As mentioned in the new choaspy documentation:  Defaults growth to the same value as ``sparse`` if omitted. 
So if `sparse=True` we have to set by default `growth` to True.
In my case, I set `sparse=True`,  `growth=True` and `rule="J"` and it works, otherwise Sobols  indices are wrong.

**Comment by raar1** [comment]
Hi @jlakhlili , both the current dev and master branches are (or should be...) now up-to-date with respect to chaospy v3.0.7.

If you have some PCE stuff you want to integrate then if you open a PR I'm happy to take a look?

**Comment by jlakhlili** [comment]
@raar1 Now we use chaospy 3.0.14 in dev branch and in master we use chaospy 3.0.7.
