### ISSUE TITLE
Create a variable containing the unique ID variable in the campaign class

### ISSUE THREAD

**Issue by mvassaux** [UCL-CCS/EasyVVUQ#31]
Would be interested in having a variable containing the ID of the EasyVVUQ campaign which is used to create the campaign directory. It would avoid to have to extract it from the campaign directory name.

**Comment by raar1** [comment]
Sure we can do that, but what are you planning to use it for? The way we currently think of it is that the campaign directory name _is_ the campaign ID. You can change the prefix ("EasyVVUQ_Runs..." or whatever) to something else if you like, but that string is part of the ID of the campaign.

Is there a reason why you can't use the whole ID? Is it because you need to build a sweep directory with a different name or something like that?

**Comment by mvassaux** [comment]
I want to reuse that ID in the naming of the fabsim jobs, to check their status easily on the remote machines.

**Comment by raar1** [comment]
Implemented in dev branch. Use campaign_ID() to get the run directory name (without path) and campaign_ID(without_prefix=True) to get it without the prefix.
