### ISSUE TITLE
only up to v0.6 available on conda

### ISSUE THREAD

**Issue by FGugole** [UCL-CCS/EasyVVUQ#355]
I was installing easyvvuq using conda (on Windows) and realized that the latest version available there is v0.6
that is quite a bummer since the latest version is v1.0 and there is quite a big difference between the two versions
![conda_easyvvuq](https://user-images.githubusercontent.com/57520908/126618005-49a90f87-2412-49bc-aefb-ebd8cd420a7f.png)

**Comment by orbitfold** [comment]
Yes, we have dropped Anaconda support since Continuous Deployment to Anaconda is a nightmare - it has a very complex and hard to debug package build system. Also there are constant issues with dependencies since a lot of packages have outdated Anaconda packages. If someone wants to bring it back I might have some tips. But I'm not building conda packages by hand every time.

**Comment by FGugole** [comment]
Got it. Pity though.
Thanks for the fast reply!

**Comment by orbitfold** [comment]
Is pip not sufficient for your case?
