### ISSUE TITLE
Handling codes which require random seeds

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#36]
We may need to template in a random variable - or do we offload this issue to the encoder. It certainly presents an issue for generic encoder.

**Comment by dww100** [comment]
My concern is that we need to ensure this is sampled but is not treated as another variable to include in a sweep or other systematic search of phase space (although it would be amusing to see if there were codes where it was a factor).

**Comment by raar1** [comment]
OK. I was thinking variables would already be clearly demarcated as "categorical" or "sampling". Maybe we can revisit this when we have a working sweep example, and see what the issues with a random seed might be?

**Comment by dww100** [comment]
Thought (may be irrelevant): ensemble sampling copies all variables, so need to ensure that isn't done for seeds.

**Comment by raar1** [comment]
It would, for example, be possible to specify via a kwarg in `vary_param()` that a given parameter should _always_ be resampled. However, that would require pretty much every relevant function to honour that request, so isn't particularly safe (in a defensive programming sense).

It does seem odd to me though that you would want to copy all the (randomly sampled) parameter values _except_ the seed. After all, the other params have completely arbitrary values. I can of course see that you'd want to force the sweep vars to have a specific, non-random value, but every other var is only really defined by its prior distribution. I know we've discussed this before though.

For now the only thing I can think of is extending `vary_param()` so that it specifies an `always_resample` type kwarg, which an ensemble copy would (should) honour, and resample that var appropriately instead of copying it.

Actually, I suppose you could refuse to add such parameters to `self._vars` at all, and instead put them wherever category parameters go. So the "seed" parameter would be treated as a special case (random) of a sweep var. Still seems messy though...

**Comment by raar1** [comment]
OK, that seems decent to me too. Let's maybe return to this when we decide how/if fixtures can basically do categorical variables (elegantly)
