### ISSUE TITLE
Allow no encoder to be specified (run var info passed to user defined execution function)

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#64]
In the case of @jlakhlili we currently have a small input file being generated for each run. This file is immediately read by the fortran code, and contains information that could in fact have been passed via commandline arguments. In the case of 1e6 runs, this is an unnecessary overhead.

I propose that the user defined execution function be also passed the same information as the encoder function is (essentially, the dictionary containing all the parameter values necessary for input creation). This would allow the execution command to be generated programmatically from this dictionary directly, therefore passing the values to the simulation code via commandline args.

In such cases you probably wouldn't want to run any encoder at all. We could have something along the lines of: ```my_campaign.set_encoder(None)```

I think this could avoid the creation of millions of tiny input files when they are not actually needed by the simulation code.

**Comment by jlakhlili** [comment]
I did some tests in the case of 1e6 runs using NML files for the generated inputs for each run.
- To store the 8 uncertain parameter values, I need just 360 MB for all NML files. I think that it is fine. I can still use this kind of inputs for the Encoder. 
- The problem is in the output. the Fortran code generate the CSV files to store quantity of  interests values. For example, the CSV files needed for the encoder of 1 QOI are heavy (4.6GB).  I think also the reading is slow. 

Maybe, the data base developed by @orbitfold can help in this case. I am thinking also to use HDF5 to store all outputs (the writing can be parallelized and in the encoder we can use panda.read_hdf with a fast cpu time).

PS. Namelists format present many advantages in Fortran, and in Python we have the great f90nml library.

**Comment by raar1** [comment]
Thanks Jalal, just to clarify - every run of the 1D model could produce a CSV file of 4.6GB? So e.g. 1e6 runs of 4.6GB files? You say these are output but are processed by the encoder - did you mean decoder? Or is this a scale bridging step we're talking about here? (such as files going to CHEASE)

**Comment by jlakhlili** [comment]
No, every run of 1D model could produce a CSV file of 3KB to 5KB (depending of the number of the quantities  of interests). So, 4.6GB is the total size of the 1e6 CSV files. Yes,  these are output processed by the decoder (it was a mistake in my text).  They are used by PCEAnalysis to create data_src.

**Comment by raar1** [comment]
I've implemented a simple ```call_for_each_run()``` method of ```campaign``` that will call a user-defined function for every run. This user-defined function is passed both the run_dir and the params dict, which means in principle that you can just pass those parameters on the commandline, for example.

I've also modified campaign so that you are allowed to set an encoder to ```None``` when creating a new app. In such a case calling ```populate_runs()``` will only create the directory structure (but do no encoding on input files). That would mean that everything could be done via this user function.
